---
title: "AK_RMIS_parce"
author: "Genoa Sullaway"
date: "11/7/2019"
output: html_document
---

```{r setup, echo=FALSE, warning=FALSE}
library(tidyverse)
library(here)

#This script will match with Jordan's recovery data and see if there is a mismatch   

#put these into NMFS areas based on the stat_area provided (~1000 recoveries), sector and longitude

#sector 3 is GOA hich means possible NMFS areas are: 640, 630, 620,610
#sector 4 is Bering - Jordan grouped it as Bering so I will just lump that way. 
#load Jordans data 
sqdat<- here::here("data","squash_data.RDS")
sqdat<- readRDS(sqdat)
#load RMIS data [eric combined it in 00.R]
rmisdat<- here::here("data","joined_releases_recoveries_locations.rds")
rmisdat <- readRDS(rmisdat)

#this is the easy match into the NMFS area because the area is in the recovery description. 
trawl_na <- rmisdat %>%
  filter(fishery %in% c(81,812,82,87,88,89) | gear %in% c(81,82,85,87,90,91,86)) %>%
  filter(is.na(latitude)) %>%
  separate(recovery_description, into = c("sea", "sector", "hemi", "Bearing", "stat_area"), sep = ",") %>%
  separate(stat_area, into = c("delete", "stat_area"), sep = 24) %>%
  select(2:8,11,12,37,30,31,33) %>%
  mutate(stat_area = case_when(
                                   recovery_location_name == "HIGH SEAS 3 N" ~ "3N", #sector 3 is GOA
                                   recovery_location_name == "HIGH SEAS 3 N W" ~ "3NW",
                                   sector== " SECTOR 4"~ "Bering",
                                   stat_area == "610" ~ "X610",
                                   stat_area == "620" ~ "X620",
                                   stat_area == "621" ~ "X621",
                                   stat_area == "630" ~ "X630",
                                   stat_area == "640" ~ "X640",
                                   stat_area == "649" ~ "X649",
                                   TRUE ~ stat_area)) %>%
  separate(recovery_date, into = c("year", "delete"), sep = 4) %>%
  mutate(individual = 1)%>%
  group_by(year, stat_area) %>%
  summarise(sum = sum(individual)) %>%
  mutate_all(funs(replace_na(.,"NA"))) 

#filter for AK Trawl fisheries 
trawl_lat_long<- rmisdat %>%
  filter(fishery %in% c(81,812,82,87,88,89) | gear %in% c(81,82,85,87,90,91,86)) %>%
  filter(!is.na(latitude)) %>%
  separate(recovery_description, into = c("delete", "sector", "lat", "long"), sep = ",") %>%
  select(-c(delete)) %>%
  mutate(stat_area = case_when(
    sector== " SECTOR 4"~ "Bering",
    longitude < -140 & longitude > -147 | longitude == -140 ~ "X640",
    longitude < -147 & longitude > -154 | longitude == -147 ~ "X630",
    longitude < -154 & longitude > -159 | longitude == -154 ~ "X620",
    longitude < -159 & longitude > -170 | longitude == -159 ~ "X610",
    longitude == -172 ~ "X541", #an odd ball on the south side of aluetian islands in sector 3
    TRUE ~ "FIX_ME")) %>%
  separate(recovery_date, into = c("year", "delete"), sep = 4) %>%
  select(-c("delete")) %>%
  filter(!fishery == 39) %>% #canadian aboriginal fishery snuck in there bc of their gear type
  filter(!stat_area == "FIX_ME") %>% # removes one recoery east of stat 640 that shouldnt have been recovered there. 
  mutate(individual = 1)%>%
  group_by(year, stat_area) %>%
  summarise(sum = sum(individual)) 
# 
# #plot lat and longs on a map to understand what the different sectors are 
# world <- map_data("world")
# north_america <- subset(world, region %in% c("USA", "Canada"))
# 
# north_america %>%
#     filter(!group== 1511, !group== 1518, !group==1515, !group==1508, !group==1502, !group==1509) %>%
#     filter(!long > -115) %>%
#     filter(!lat < 34) %>%
#     filter(!lat > 62) %>%
#     filter(!long < -173) %>%
#     ggplot( ) + 
#     geom_polygon(aes(x = long, y = lat, group = group), fill = "white", color = "black") + 
#     coord_fixed(1.3)+
#     geom_point(data = trawl_lat_long, mapping = aes(x = longitude, y = latitude, color = sector)) +
#     theme_bw() 

#bring in Jordans summary
obsfun <- function(sample){
  dots <- enquo(sample)
  sqdat %>% 
    select(area,year,!!dots) %>% # Search help files for "quasiquotation" to explain '!!'
    filter(!is.na(!!dots)) %>% 
    group_by(area,year) %>% 
    count(!!dots) %>% 
    spread(area,n)
}

```

Summary table of CWT recoveries from AK trawl fleets based on RMIS database
```{r trawl summary, echo = FALSE,  warning=FALSE}
  #combine two data frames to get totals
trawl <- full_join(trawl_lat_long, trawl_na, by = c("year", "stat_area")) %>%
  mutate_all(funs(replace_na(.,0))) %>%
  mutate(sum = as.numeric(sum.x) + as.numeric(sum.y)) %>%
  select(-c(3:4)) %>%
  spread(stat_area, sum) %>%
  mutate_all(funs(replace_na(.,0))) %>%
  select(-c(2,3)) #right now just going to use main NMFS areas (taking out some of the unknowns like 3N) so comparison is easier

 knitr::kable(
  trawl[1:37, 1:10], caption = 'AK Trawl Recoveries from RMIS'
) 

```

Summary table based on fish where tissue was sampled -and an adipose was not present (so minimum # of CWT's, but doesnt include fish that had a CWT and an adipose was present)
```{r, echo = FALSE,warning=FALSE}

jordan_trawl<-obsfun(samplenum) %>%  dplyr::select(-samplenum) %>% data.frame
sqdat<-sqdat %>%
  mutate(sampled = case_when( type_4_fin_clips== "Y" | type_11_other_tissue== "Y" | type_13_adipose_present == "N" ~ 1,
                              TRUE ~ 0)) %>%
  filter(!sampled == 0)
sampled_sqdat<-obsfun(sampled) %>%  dplyr::select(-sampled) %>% data.frame %>%  mutate_all(funs(replace_na(.,0))) 

 knitr::kable(
  sampled_sqdat[1:12, 1:10], caption = 'No adipose chinook tissue samples'
) 

```

